default:
  http_metas:
    content-type: text/html

  metas:
    title:        ZADKIEL | ME
    description:  Le blog de Zadkiel !
    keywords:     flideli, blog, web2.0 
    language:     fr
    robots:       index, follow

  stylesheets:    [blueprint/screen: { media: screen }, blueprint/print: { media: print }, default: { media: screen }, blueprint/plugins/fancy-type/screen: { media: screen }]

  javascripts:    [ui.js]

  has_layout:     on
  layout:         layout
